import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import FloatingNavbar from "@/components/FloatingNavbar";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Bibaho-Bondhon",
  description: "Generated by shahadatw6",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div>

        </div>
        <FloatingNavbar />
        <div className="relative w-full flex items-center justify"></div>
        {children}
      </body>
    </html>
  );
}
